name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Detect build output
      id: detect-output
      run: |
        if [ -d "./dist" ]; then
          echo "path=./dist" >> $GITHUB_OUTPUT
        elif [ -d "./build" ]; then
          echo "path=./build" >> $GITHUB_OUTPUT
        else
          echo "No dist or build folder found!"
          exit 1
        fi

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ steps.detect-output.outputs.path }}
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
